version: '3.4'

services: 
  patientapi:
    image: ${DOCKER_REGISTRY-}patientapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    ports:
      - "8080:80"
      - "8081:80"
    depends_on:
      - sql

  patientconsole:
    image: ${DOCKER_REGISTRY}patientconsole
    build:
      context: ./Patient.Console
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    depends_on:
      - patientapi
    stdin_open: true
    tty: true

  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=A&VeryComplex123Password
    ports:
      - "1433:1433"
    volumes:
      - dbdata:/var/opt/mssql
volumes:
  dbdata: